---
#####################
#  RHOSP Repository #
#####################
osp_release: "16.2"
rhel_release: "8.4"
puddle: "RHOS-16.2-RHEL-8-20221111.n.1"

#####################
#  Host Credentials #
#####################
testpmd_ssh_user: "cloud-user"
testpmd_ssh_passwd: "100yard-"
testpmd_ssh_key: "/home/stack/stack.key"
ssh_user: "root"
root_password: "100yard-"

##################################
#  dpdk-testpmd OS Configuration #
##################################
testpmd_kernel: "true"
testpmd_kernel_args: "'default_hugepagesz=1GB hugepagesz=1G hugepages=8 iommu=pt intel_iommu=on isolcpus=3-5 ipv6.disable=1 vfio.enable_unsafe_noiommu_mode=Y'"
testpmd_isolated_cores: "3-5"
testpmd_tuned_profile: "cpu-partitioning"
testpmd_custom_script: "true"
testpmd_script_location: "scripts/dpdk-testpmd.sh"

################################
#  Trafficgen OS Configuration #
################################
tgen_kernel: "false"
tgen_kernel_args: "'default_hugepagesz=1GB hugepagesz=1G hugepages=100 iommu=pt intel_iommu=on isolcpus=8-55 vfio.enable_unsafe_noiommu_mode=Y'"
tgen_isolated_cores: "8-55"
tgen_tuned_profile: "cpu-partitioning"

tgen_pci: "true"
tgen_driver: "vfio-pci"
tgen_pci_list:
  - "0000:06:00.0"
  - "0000:06:00.1"
  - "0000:83:00.0"
  - "0000:83:00.1"
  - "0000:08:00.0"
  - "0000:08:00.1"
  - "0000:81:00.0"
  - "0000:81:00.1"

