---
<<<<<<< HEAD
#####################
#  RHOSP Repository #
#####################
osp_release: "16.2"
rhel_release: "8.4"
puddle: "RHOS-16.2-RHEL-8-20221111.n.1"

#####################
#  Host Credentials #
#####################
testpmd_ssh_user: "cloud-user"
testpmd_ssh_passwd: "100yard-"
testpmd_ssh_key: "/home/stack/stack.key"
ssh_user: "root"
root_password: "100yard-"

##################################
#  dpdk-testpmd OS Configuration #
##################################
testpmd_kernel: "true"
testpmd_kernel_args: "'default_hugepagesz=1GB hugepagesz=1G hugepages=8 iommu=pt intel_iommu=on isolcpus=3-5 ipv6.disable=1 vfio.enable_unsafe_noiommu_mode=Y'"
testpmd_isolated_cores: "3-5"
testpmd_tuned_profile: "cpu-partitioning"
testpmd_custom_script: "true"
testpmd_script_location: "scripts/dpdk-testpmd.sh"

################################
#  Trafficgen OS Configuration #
################################
tgen_kernel: "true"
tgen_kernel_args: "'default_hugepagesz=1GB hugepagesz=1G hugepages=100 iommu=pt intel_iommu=on isolcpus=8-55 vfio.enable_unsafe_noiommu_mode=Y'"
tgen_isolated_cores: "8-55"
tgen_tuned_profile: "cpu-partitioning"

tgen_pci: "true"
tgen_driver: "vfio-pci"
tgen_pci_list:
  - "0000:06:00.0"
  - "0000:06:00.1"
  - "0000:83:00.0"
  - "0000:83:00.1"
  - "0000:08:00.0"
  - "0000:08:00.1"
  - "0000:81:00.0"
  - "0000:81:00.1"
=======
## ---------------------------------- RHOSP and RHEL Version ---------------------------------------------------------- ##
osp_release: "17.0"
rhel_release: "9.0"
puddle: "RHOS-17.0-RHEL-9-20220830.n.1"
root_password: "100yard-"

## ----------------------------------- Inventory Credentials --------------------------------------------------------- ##
testpmd_ssh_user: "cloud-user"
testpmd_ssh_passwd: "null"
testpmd_ssh_key: "/home/stack/key.pem"

trafficgen_ssh_user: "cloud-user"
trafficgen_ssh_passwd: "null"
trafficgen_ssh_key: "/home/stack/key.pem"

BM_ssh_user: "root"
BM_ssh_passwd: "100yard-"

pbench_repo: "false"

## ----------------------------------- TestPMD OS Configurations --------------------------------------------------------- ##
## TestPMD VM Configuration
kernel_args: "'default_hugepagesz=1GB hugepagesz=1G hugepages=4 iommu=pt intel_iommu=on isolcpus=3-5'"
isolated_cores: "3-5"
tuned_profile: "cpu-partitioning"

## -------------------------------------- Trafficgen OS Configuration------------------------------------------------------ ##
#Vitual Machine
trafficgen_vm: "false"
tgen_kernel_args: "'default_hugepagesz=1GB hugepagesz=1G hugepages=17 iommu=pt intel_iommu=on isolcpus=2-19'"
tgen_isolated_cores: "2-19"
tgen_tuned_profile: "cpu-partitioning"

#Physical Machine
trafficgen_bm: "false"
bm_isolated_cores: "6-35,42-71"
bm_tuned_profile: "cpu-partitioning"
bm_kernel_args: "'default_hugepagesz=1GB hugepagesz=1G hugepages=150 iommu=pt intel_iommu=on isolcpus=6-35,42-71'"

## --------------------------------------- Build Trafficgen Profile ----------------------------------------------------- ##
trafficgen_backend: "trex-txrx"
custom_profile: "../scripts/profile.json"

trex_txrx_profile_script: "pbench-trafficgen --traffic-generator=trex-txrx-profile --devices=0000:00:05.0,0000:00:06.0 --traffic-profile=/opt/trafficgen/trex-profiles/test/test-profile-01.json --rate=50 --rate-unit=% --samples=1 --max-loss-pct=0.002 --config=Test --tool-period=binary-search --skip-git-pull --search-runtime=60 --validation-runtime=120 -- --disable-flow-cache --measure-latency 0 --no-promisc --loss-granularity=segment"

trex_txrx_script: "pbench-trafficgen --traffic-generator=trex-txrx --devices=0000:00:05.0,0000:00:06.0 --samples=1 --max-loss-pct=0.002 --config=Test --frame-sizes=64 --num-flows=128 --traffic-directions=bidirectional --flow-mods=src-ip --tool-period=binary-search --skip-git-pull --search-runtime=120 --validation-runtime=1200 --rate=100 --rate-unit=% -- --send-teaching-measurement --send-teaching-warmup --teaching-measurement-packet-type=generic --teaching-warmup-packet-type=generic --disable-flow-cache"

## ---------------------------------------- Pbench & Trafficgen Configuration ---------------------------------------------------- ##
git_pbench_repo: "https://code.engineering.redhat.com/gerrit/perf-dept"
git_tgen_repo: "https://github.com/atheurer/trafficgen.git"

## --------------------------------------- Build TestPMD Script ----------------------------------------------------- ##
testpmd_script: "True"
testpmd_profile: "dpdk-testpmd -l 3,4,5 -n 4 --huge-dir=/dev/hugepages -w 0000:00:05.0 -w 0000:00:06.0 --socket-mem 2048,0 -- --nb-cores=2 --forward-mode=io --rxd=1024 --txd=1024 --rxq=1 --txq=1 --burst=64 --mbcache=512 -a --rss-udp --disable-crc-strip --stats-period 1"

>>>>>>> 4064eeabed8375e8849793026bf17563b91672a6

