---
#####################
#  RHOSP Repository #
#####################
#osp_release: "17.1"
rhel_release: "9.2"
#puddle: "RHOS-16.2-RHEL-8-20230526.n.1"
#puddle: "RHOS-17.1-RHEL-9-20230511.n.1"

install_cert: "true"
cert_script: "scripts/custom_cert.sh"


#####################
#  Host Credentials #
#####################
testpmd_ssh_user: "cloud-user"
testpmd_ssh_passwd: "100yard-"
testpmd_ssh_key: "/home/stack/key.pem"
ssh_user: "root"
root_password: "100yard-"

##################################
#  dpdk-testpmd OS Configuration #
##################################
mlnx_ofed_guest_config: "false"
dpdk_ver: "22.11.2"
guest_ofed_version: "23.10-2.1.3.1"
rhel_guest_repo: "http://download-node-02.eng.bos.redhat.com/rhel-9/rel-eng/RHEL-9/latest-RHEL-9.2/repofile.repo"
# available repo servers: download.eng.tlv.redhat.com, download-node-02.eng.bos.redhat.com

testpmd_kernel: "true"
testpmd_kernel_args: "'default_hugepagesz=1GB hugepagesz=1G hugepages=20 iommu=pt intel_iommu=on isolcpus=10-25 ipv6.disable=1 vfio.enable_unsafe_noiommu_mode=Y nmi_watchdog=0 audit=0 mce=off processor.max_cstate=1 idle=poll intel_idle.max_cstate=0 tsc=reliable rcupdate.rcu_normal_after_boot=1 systemd.cpu_affinity=0,1,2,3,4,5,6,7,8,9 isolcpus=managed_irq,10-25 rcutree.kthread_prio=11 systemd.unified_cgroup_hierarchy=0 systemd.legacy_systemd_cgroup_controller=1'"
testpmd_isolated_cores: "10-25"
testpmd_tuned_profile: "cpu-partitioning"
testpmd_custom_script: "false"
testpmd_script_location: "scripts/dpdk-testpmd.sh"
testpmd_pci: "false"
dpdk_driver_module_list:
  - "vfio"
  - "vfio-pci"
testpmd_driver: "vfio-pci"
testpmd_pci_list:
  - "0000:05:00.0"
  - "0000:06:00.0"

################################
#  Trafficgen OS Configuration #
################################
tgen_kernel: "false"
tgen_kernel_args: "'default_hugepagesz=1GB hugepagesz=1G hugepages=100 iommu=pt intel_iommu=on isolcpus=8-55 vfio.enable_unsafe_noiommu_mode=Y'"
tgen_isolated_cores: "8-55"
tgen_tuned_profile: "cpu-partitioning"

tgen_pci: "true"
tgen_driver: "vfio-pci"
tgen_pci_list:
  - "0000:3b:00.0"
  - "0000:3b:00.1"
  - "0000:5e:00.0"
  - "0000:5e:00.1"
  - "0000:af:00.0"
  - "0000:af:00.1"
  - "0000:86:00.0"
  - "0000:86:00.1"

mlnx_ofed_tgen_config: "false"
tgen_dpdk_ver: "22.11.2"
tgen_ofed_version: "23.04-1.1.3.0"
rhel_tgen_repo: "http://download-node-02.eng.bos.redhat.com/rhel-9/rel-eng/RHEL-9/latest-RHEL-9.2/repofile.repo"

##############################
#  FDP Debugging for DUT     #
##############################
# Enabled OVS debug repository and installed required RPMs for debugging.
# RPMs get install in all investory host and can modified as per user choice.
fdp_debug: "true"
package_list:
  - "python3-pip"
  - "openvswitch3.1-test"
  - "perf"
  - "gcc"
  - "make"
  - "cmake"
  - "kernel-headers"
  - "gcc-c++"
  - "cmake"
  - "glibc-devel"
  - "glibc-headers"
  - "kernel-devel"
  - "cscope"
  - "perl-open"
    #  - "http://download-node-02.eng.bos.redhat.com/brewroot/packages/openvswitch3.1/3.1.0/54.el9fdp/x86_64/openvswitch3.1-debuginfo-3.1.0-54.el9fdp.x86_64.rpm"
    #  - "http://download-node-02.eng.bos.redhat.com/brewroot/packages/openvswitch3.1/3.1.0/54.el9fdp/x86_64/openvswitch3.1-debugsource-3.1.0-54.el9fdp.x86_64.rpm"
pip_binaries:
  - "text_histogram3"

##################
# OVS-DPDK Debug #
##################
# Due to pre-requsites of debug rpms, ensure "fdp_debug" params should be true before enabled ovs_dpdk_debug flag.
ovs_dpdk_debug: "false"

# For Perf samples analysis for PMD cores, this is sample script need to copied to Compute host.
pmd_perf_script: "scripts/ovs/"

# Action against local port of ovs-dpdk provider bridge as the port always triggered syscall
#br_local_port_status: "down"
#provider_br_list:
#  - "br-intl1"
#  - "br-intl2"
#  - "br-mlx1"
#  - "br-mlx2"
#  - "br-intlbond"
#  - "br-mlxbond"
#  - "br-dpdkbond"
#  - "br-provider1"
#  - "br-provider2"


#######################
# Mellanox Nic Config #
#######################
mlnx_compute: "false"
mlnx_ofed_repository: "false"
# Update the OFED version as per the avaliable details: https://network.nvidia.com/products/infiniband-drivers/linux/mlnx_ofed/
mlnx_ofed_version: "23.04-1.1.3.0"
mlnx_package_list:
  - "mft"
mlnx_sriov_vf: "false"
mlnx_vf_num: "20"
mlnx_pci_list:
  - "0000:98:00.0"
  - "0000:98:00.1"
