---
#####################
#  RHOSP Repository #
#####################
#osp_release: "17.1"
rhel_release: "9.2"
#puddle: "RHOS-16.2-RHEL-8-20230526.n.1"
#puddle: "RHOS-17.1-RHEL-9-20230511.n.1"

install_cert: "true"
cert_script: "scripts/custom_cert.sh"


#####################
#  Host Credentials #
#####################
testpmd_ssh_user: "cloud-user"
testpmd_ssh_passwd: "100yard-"
testpmd_ssh_key: "/home/stack/key.pem"
ssh_user: "root"
root_password: "100yard-"

##################################
#  dpdk-testpmd OS Configuration #
##################################
guest_ofed: "true"
guest_ofed_version: "23.04-1.1.3.0"
testpmd_kernel: "true"
testpmd_kernel_args: "'default_hugepagesz=1GB hugepagesz=1G hugepages=6 iommu=pt intel_iommu=on isolcpus=3-11 ipv6.disable=1 vfio.enable_unsafe_noiommu_mode=Y'"
  #testpmd_kernel_args: "'default_hugepagesz=1GB hugepagesz=1G hugepages=6 iommu=pt intel_iommu=on isolcpus=3-11 ipv6.disable=1'"
testpmd_isolated_cores: "3-11"
testpmd_tuned_profile: "cpu-partitioning"
testpmd_custom_script: "false"
testpmd_script_location: "scripts/dpdk-testpmd.sh"
testpmd_pci: "false"
dpdk_driver_module_list:
  - "vfio"
  - "vfio-pci"
testpmd_driver: "vfio-pci"
testpmd_pci_list:
  - "0000:04:00.0"
  - "0000:05:00.0"

################################
#  Trafficgen OS Configuration #
################################
tgen_kernel: "false"
tgen_kernel_args: "'default_hugepagesz=1GB hugepagesz=1G hugepages=100 iommu=pt intel_iommu=on isolcpus=8-55 vfio.enable_unsafe_noiommu_mode=Y'"
tgen_isolated_cores: "8-55"
tgen_tuned_profile: "cpu-partitioning"

tgen_pci: "true"
tgen_driver: "vfio-pci"
tgen_pci_list:
  - "0000:06:00.0"
  - "0000:06:00.1"
  - "0000:83:00.0"
  - "0000:83:00.1"
  - "0000:08:00.0"
  - "0000:08:00.1"
  - "0000:85:00.0"
  - "0000:85:00.1"

##############################
#  Additional Configuration  #
##############################
# Enabled OVS debug repository and installed required RPMs for debugging.
# RPMs get install in all investory host and can modified as per user choice.
fdp_debug: "true"
package_list:
  - "strace"
  - "wireshark-cli"
  - "podman"
  - "git"
  - "wget"
  - "vim"
  - "tcpdump"
  - "dpdk-tools"
  - "tmux"
  - "lsof"
  - "tcl"
  - "dpdk"
  - "numactl-devel"
  - "binutils"
  - "driverctl"
  - "python3-pip"
#  - "openvswitch3.1-debuginfo-3.1.0-23.el9fdp.x86_64"
#  - "openvswitch3.1-debugsource-3.1.0-23.el9fdp.x86_64"
#  - "openvswitch3.1-test-0:3.1.0-23.el9fdp.noarch"
#  - "perf-5.14.0-283.el9.x86_64"
#  - "gcc"
#  - "make"
#  - "cmake"
#  - "kernel-headers"
#  - "gcc-c++"
#  - "cmake"
#  - "glibc-devel"
#  - "glibc-headers"
#  - "kernel-devel"
#  - "cscope"
pip_binaries:
  - "text_histogram3"

##################
# OVS-DPDK Debug #
##################
# Due to pre-requsites of debug rpms, ensure "fdp_debug" params should be true before enabled ovs_dpdk_debug flag.
ovs_dpdk_debug: "false"

# For Perf samples analysis for PMD cores, this is sample script need to copied to Compute host.
pmd_perf_script: "scripts/pmd_perf.sh"
perf_git_script: "https://github.com/chaudron/perf_scripts"

# Action against local port of ovs-dpdk provider bridge as the port always triggered syscall
#br_local_port_status: "down"
#provider_br_list:
#  - "br-dpdkbond"
#  - "br-provider1"
#  - "br-provider2"


#######################
# Mellanox Nic Config #
#######################
mlnx_compute: "true"
mlnx_ofed_repository: "true"
# Update the OFED version as per the avaliable details: https://network.nvidia.com/products/infiniband-drivers/linux/mlnx_ofed/
mlnx_ofed_version: "23.04-1.1.3.0"
mlnx_package_list:
  - "mft"
mlnx_sriov_vf: "false"
mlnx_vf_num: "20"
mlnx_pci_list:
  - "0000:98:00.0"
  - "0000:98:00.1"
