---
- hosts: osp-compute
  become: True
  gather_facts: True
  any_errors_fatal: yes
  tasks:
    - name: Copied OVN RC file
      copy:
        src: scripts/ovnrc
        dest: /root/
        owner: root
        group: root
        mode: 0644
    - block:
        - name: Action against local port of ovs-dpdk provider bridges
          loop: "{{ provider_br_list }}"
          shell: |
            ovs-ofctl mod-port {{ item }} {{ item }} {{ br_local_port_status }}
            ovs-ofctl show {{ item }}
          when: provider_br_list is defined and br_local_port_status is defined
      when: inventory_hostname in groups['osp-compute']

    - block:
        - name: Copied Perf Script
          copy:
            src: "{{ pmd_perf_script }}"
            dest: /root/
            owner: root
            group: root
            mode: 0755
          when: pmd_perf_script is defined

        - name: Clone Git repository of Perf Script
          git:
            repo: "{{ perf_git_script }}"
            dest: /root/perf_script
            version: master
            clone: yes
            update: yes
          when: perf_git_script is defined
      when: fdp_debug == "true" and ovs_dpdk_debug == "true" and inventory_hostname in groups['osp-compute']

    - block:
        - name: Download OFED bunddles
          ansible.builtin.unarchive:
            #src: https://content.mellanox.com/ofed/MLNX_OFED-23.04-0.5.3.3/MLNX_OFED_LINUX-23.04-0.5.3.3-rhel9.1-x86_64.tgz
            src: https://content.mellanox.com/ofed/MLNX_OFED-{{ mlnx_ofed_version }}/MLNX_OFED_LINUX-{{ mlnx_ofed_version }}-rhel{{ rhel_release }}-x86_64.tgz
            dest: /var/lib/
            remote_src: yes
          when: mlnx_ofed_version is defined and rhel_release is defined

        - name: Create OFED repository
          ansible.builtin.yum_repository:
            name: mlx-ofed-{{ mlnx_ofed_version }}-rhel{{ rhel_release }}
            file: mlx_ofed
            description: Mellanox Ofed Repository
            baseurl: file:////var/lib/MLNX_OFED_LINUX-{{ mlnx_ofed_version }}-rhel{{ rhel_release }}-x86_64/RPMS
            #baseurl: file:////var/lib/MLNX_OFED_LINUX-23.04-0.5.3.3-rhel9.1-x86_64/RPMS
            enabled: yes
            gpgcheck: no
          when: mlnx_ofed_repository == "true" and mlnx_ofed_version is defined and rhel_release is defined

        - name: Install Mellanox Utiility rpms
          loop: "{{ mlnx_package_list }}"
          dnf:
            name: "{{ item }}"
            state: present

        - name: Set SRIOV VFs on Mellanox Card
          loop: "{{ mlnx_pci_list }}"
          shell: |
            mlxconfig -d {{ item }} -y set SRIOV_EN=1 NUM_OF_VFS={{ mlnx_vf_num }}
          register: mlnxupdate
          when: mlnx_sriov_vf == "true" and mlnx_vf_num is defined

        - name: Reboot mlx_compute node post VF config
          reboot:
            pre_reboot_delay: 60
          when: mlnxupdate.changed
      when: mlnx_compute == "true" and inventory_hostname in groups['osp-compute']
