---
- hosts: testpmd,trafficgen
  become: true
  gather_facts: True

  tasks:
    - block:
        - name: Update TestPMD VMs Kernel boot parameter
          shell: |
             grubby --remove-args={{ testpmd_kernel_args }} --args {{ testpmd_kernel_args }} --update-kernel DEFAULT ; grubby --info DEFAULT
          register: testpmd_grub_update
          when: testpmd_kernel == "true" and testpmd_kernel_args is defined
            
        - name: Reboot TestPMD VMs
          ansible.builtin.reboot:
            reboot_timeout: 600
          when: testpmd_grub_update.changed
      when: ansible_os_family == "RedHat" and inventory_hostname in groups['testpmd']

    - block:
        - name: Update Trafficgen Hosts Kernel boot parameter
          shell: |
             grubby --remove-args={{ tgen_kernel_args }} --args {{ tgen_kernel_args }} --update-kernel DEFAULT ; grubby --info DEFAULT
          register: tgen_grub_update
          when: tgen_kernel == "true" and tgen_kernel_args is defined

        - name: Reboot Trafficgen Hosts
          reboot:
             pre_reboot_delay: 60
          when: tgen_grub_update.changed
      when: ansible_os_family == "RedHat" and inventory_hostname in groups['trafficgen']
