---
- hosts: all
  become: true
  gather_facts: True
  any_errors_fatal: yes

  tasks:
    - name: Set timezone to UTC
      timezone:
        name: UTC

    - block:
        - name: Install rhos-release
          shell: |
             dnf erase -y rhos-release; dnf install -y http://download.devel.redhat.com/rcm-guest/puddles/OpenStack/rhos-release/rhos-release-latest.noarch.rpm

        - name: Configure RHOSP {{ osp_release }} repos in all hosts
          shell: |
             rhos-release -x; rhos-release {{ osp_release }} -p {{ puddle }} -r {{ rhel_release }}

        - name: Enable Virt and Container-tool modules for {{ rhel_release }}
          shell: |
             dnf -y module disable virt:rhel container-tools:rhel8; dnf -y module enable virt:av container-tools:3.0
          when: osp_release == "16.2" and rhel_release == "8.4"

        - name: Enable Virt and Container-tool modules for {{ rhel_release }}
          shell: |
             dnf -y module disable virt:rhel container-tools:rhel8; dnf -y module enable virt:8.2 container-tools:2.0
          when: osp_release == "16.1" and rhel_release == "8.2"

      when: inventory_hostname in groups['testpmd'] or inventory_hostname in groups['trafficgen'] or inventory_hostname in groups['osp-compute']

    - block:
        - name: Update latest packages in Trafficgen and DPDK hosts
          dnf:
            name: "*"
            state: latest
            update_cache: yes
          register: osupdated
        - name: Post update host reboot
          reboot:
            pre_reboot_delay: 30
          when: osupdated.changed

      when: inventory_hostname in groups['testpmd'] or inventory_hostname in groups['trafficgen']

    - block:
        - name: Update rhosp-rhel8-fdp-debug Repo
          blockinfile:
            path: /etc/yum.repos.d/rhos-release-rhel-{{ rhel_release }}.repo
            marker: "# {mark} ANSIBLE MANAGED BLOCK #"
            block: |
              [rhosp-rhel-{{ rhel_release }}-fdp-debug]
              name=Red Hat Enterprise Linux Fast Datapath debug $releasever - $basearch
              baseurl=http://rhsm-pulp.corp.redhat.com/content/dist/layered/rhel8/$basearch/fast-datapath/debug/
              enabled=1
              gpgcheck=0
          when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

        - name: Update rhosp-rhel9-fdp-debug Repo
          blockinfile:
            path: /etc/yum.repos.d/rhos-release-rhel-{{ rhel_release }}.repo
            marker: "# {mark} ANSIBLE MANAGED BLOCK #"
            block: |
              [rhosp-rhel-{{ rhel_release }}-fdp-debug]
              name=Red Hat Enterprise Linux Fast Datapath debug $releasever - $basearch
              baseurl=http://rhsm-pulp.corp.redhat.com/content/dist/layered/rhel9/$basearch/fast-datapath/debug/
              enabled=1
              gpgcheck=0
          when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "9"

        - name: Install additional FDP packages for Debugging
          loop: "{{ package_list }}"
          dnf:
            name: "{{ item }}"
            state: present

        - name: Install additional Python binaries
          loop: "{{ pip_binaries }}"
          pip:
            name: "{{ item }}"
            state: present

      when: fdp_debug == "true"
