---
- hosts: testpmd,osp-compute
  become: True
  gather_facts: True
  any_errors_fatal: yes
  tasks:
    - block:
        - name: Load modules in guest vm
          loop: "{{ dpdk_driver_module_list }}"
          shell: |
            modprobe "{{ item }}"
          when: dpdk_driver_module_list is defined

        - name: Override Guest VM PCI driver to {{ testpmd_driver }}
          loop: "{{ testpmd_pci_list }}"
          shell: |
            driverctl set-override "{{ item }}" {{ testpmd_driver }}
          when: testpmd_pci == "true"

        - name: List of override driver
          shell: |
            driverctl list-overrides
      when: testpmd_pci == "true" and inventory_hostname in groups['testpmd']

    - block:
        - name: Copied custom dpdk-testpmd script to VM
          copy:
            src: "{{ testpmd_script_location }}"
            dest: /root/dpdk_testpmd.sh
            owner: root
            group: root
            mode: 0755
        - name: Execute dpdk-testpmd script
          command: sh /root/dpdk_testpmd.sh
      when: testpmd_custom_script == "true" and inventory_hostname in groups['testpmd']

    - block:
        - name: Copied custom dpdk-testpmd script to Compute
          copy:
            src: "{{ testpmd_script_location }}"
            dest: /root/dpdk_testpmd.sh
            owner: root
            group: root
            mode: 0755
      when: testpmd_custom_script == "true" and inventory_hostname in groups['osp-compute']

    - block:
        - name: Download OFED bunddles in Guest VM
          ansible.builtin.unarchive:
            src: https://content.mellanox.com/ofed/MLNX_OFED-{{ guest_ofed_version }}/MLNX_OFED_LINUX-{{ guest_ofed_version }}-rhel{{ rhel_release }}-x86_64.tgz
            dest: /var/lib/
            remote_src: yes

        - name: Create OFED repository
          ansible.builtin.yum_repository:
            name: mlx-ofed-{{ guest_ofed_version }}-rhel{{ rhel_release }}
            file: mlx_ofed
            description: Mellanox Ofed Repository
            baseurl: file:////var/lib/MLNX_OFED_LINUX-{{ guest_ofed_version }}-rhel{{ rhel_release }}-x86_64/RPMS
            enabled: yes
            gpgcheck: no

        - name: Install Mellanox Utiility rpms
          dnf:
            name: mlnx-ofed-all
            state: present
            allowerasing: true

        - name: Install Mellanox Utiility rpms
          dnf:
            name:
              - meson
              - python3-pyelftools
              - python-pyelftools
              - gcc
              - glibc-devel
              - kernel-headers
              - kernel-devel
              - numad
              - numactl-libs
              - numactl-devel
              - libpcap
              - wget
            state: present

        - name: Download DPDK-{{ dpdk_ver }}
          get_url:
            url: https://fast.dpdk.org/rel/dpdk-{{ dpdk_ver }}.tar.xz
            dest: /opt/dpdk-{{ dpdk_ver }}.tar.xz

        - name: Extract dpdk-{{ dpdk_ver }}.tar.xz
          ansible.builtin.unarchive:
            src: /opt/dpdk-{{ dpdk_ver }}.tar.xz
            dest: /opt/
            remote_src: yes

        - name: Compile dpdk-{{ dpdk_ver }}
          shell: |
            meson build
            ninja -C build
          args:
            chdir: /opt/dpdk-stable-{{ dpdk_ver }}/

        - name: Create soft link for dpdk-testpmd
          file:
            src: /opt/dpdk-stable-{{ dpdk_ver }}/build/app/dpdk-testpmd
            dest: /usr/bin/dpdk-testpmd
            state: link

        - name: Reboot Guest VMs
          ansible.builtin.reboot:
            reboot_timeout: 600

      when: mlnx_ofed_guest_config == "true" and inventory_hostname in groups['testpmd']


