---
- hosts: testpmd
  become: True
  gather_facts: True
  any_errors_fatal: yes
  tasks:
    - block:
        - name: Copied custom dpdk-testpmd script to VM
          copy:
            src: "{{ testpmd_script_location }}"
            dest: /root/dpdk_testpmd.sh
            owner: root
            group: root
            mode: 0755
        - name: Execute dpdk-testpmd script
          command: sh /root/dpdk_testpmd.sh
      when: testpmd_custom_script == "true" and inventory_hostname in groups['testpmd']
