---
- hosts: trafficgen
  become: true
  gather_facts: True
  any_errors_fatal: yes

  tasks:
    - block:
        - name: Load {{ tgen_driver }} module
          shell: |
             modprobe {{ tgen_driver }}
          when: tgen_driver is defined

        - name: Override PCI driver to {{ tgen_driver }}
          loop: "{{ tgen_pci_list }}"
          shell: |
             driverctl set-override "{{ item }}" {{ tgen_driver }}
          when: tgen_pci == "true"

        - name: List of override driver
          shell: |
             driverctl list-overrides
      when: inventory_hostname in groups['trafficgen']

