---
- name: Configured Trafficgen script with trex-txrx-profile backend
  copy:
    dest: /root/trex-txrx-profile.sh
    owner: root
    group: root
    mode: 0755
    content: |
      {{ trex_txrx_profile_script }}

- name: Copy {{ custom_profile }} to trafficgen host
  copy:
    src: "{{ custom_profile }}"
    dest: /opt/trafficgen/trex-profiles/test/
    owner: root
    group: root
    mode: 0755
