- hosts: testpmd,trafficgen
  become: true
  gather_facts: True

  tasks:
    - block:
        - name: Install Pre-requisite packages
          dnf:
            name:
              - tuned
              - tuned-profiles-cpu-partitioning
          when: testpmd_tuned_profile == "cpu-partitioning"

        - name: Comment isolated_cores entry
          lineinfile: dest=/etc/tuned/cpu-partitioning-variables.conf regexp='^isolated_cores' line='#isolated_cores=${f:calc_isolated_cores:1}'
          when: testpmd_tuned_profile == "cpu-partitioning"

        - name: Update /etc/tuned/cpu-partitioning-variables.conf
          blockinfile:
            path: /etc/tuned/cpu-partitioning-variables.conf
            marker: "# {mark} ANSIBLE MANAGED BLOCK #"
            block: |
              isolated_cores={{ testpmd_isolated_cores }}
              no_balance_cores={{ testpmd_isolated_cores }}
          when: testpmd_tuned_profile == "cpu-partitioning"

        - name: Enable {{ testpmd_tuned_profile }} profile
          shell: |
             tuned-adm profile {{ testpmd_tuned_profile }}
        - name: Updating initramfs/initrd image
          shell: |
             dracut -f
      when: inventory_hostname in groups['testpmd']

    - block:
        - name: Install Pre-requisite packages
          dnf:
            name:
              - tuned
              - tuned-profiles-cpu-partitioning
          when: tgen_tuned_profile == "cpu-partitioning"

        - name: Comment isolated_cores entry
          lineinfile: dest=/etc/tuned/cpu-partitioning-variables.conf regexp='^isolated_cores' line='#isolated_cores=${f:calc_isolated_cores:1}'
          when: tgen_tuned_profile == "cpu-partitioning"

        - name: Update /etc/tuned/cpu-partitioning-variables.conf
          blockinfile:
            path: /etc/tuned/cpu-partitioning-variables.conf
            marker: "# {mark} ANSIBLE MANAGED BLOCK #"
            block: |
              isolated_cores={{ bm_isolated_cores }}
              no_balance_cores={{ bm_isolated_cores }}
          when: tgen_tuned_profile == "cpu-partitioning"

        - name: Enable {{ tgen_tuned_profile }} profile
          shell: |
             tuned-adm profile {{ tgen_tuned_profile }}

        - name: Updating initramfs/initrd image
          shell: |
             dracut -f
      when: tgen_kernel == "true" and inventory_hostname in groups['trafficgen']

